# Generated by Django 5.0.7 on 2024-08-12 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fore',
            name='mail',
            field=models.EmailField(max_length=150),
        ),
        migrations.AlterField(
            model_name='fore',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
