# Generated by Django 5.0.7 on 2024-08-12 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adr', '0002_alter_fore_mail_alter_fore_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('mail', models.EmailField(max_length=150)),
                ('mesg', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='fore',
        ),
    ]
