# Generated by Django 5.0.7 on 2024-08-12 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Adr', '0003_ace_delete_fore'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ace',
            new_name='contact',
        ),
    ]
