# Generated by Django 5.0.7 on 2024-08-12 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Adr', '0004_rename_ace_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='mail',
            new_name='email',
        ),
    ]
