# Generated by Django 5.0.7 on 2024-08-20 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Adr', '0006_images'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='ToDoList',
        ),
    ]
