# Generated by Django 5.0.7 on 2024-08-20 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adr', '0007_delete_item_delete_todolist'),
    ]

    operations = [
        migrations.CreateModel(
            name='masterdatamanagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=30)),
                ('subhead1', models.CharField(max_length=35)),
                ('Bgimage', models.ImageField(upload_to='media/')),
                ('subtxt1', models.CharField(max_length=400)),
                ('subhead2', models.CharField(max_length=50)),
                ('subtxt2', models.CharField(max_length=400)),
                ('subimage2', models.ImageField(upload_to='media/')),
                ('subhead3', models.CharField(max_length=50)),
                ('subtxt3', models.CharField(max_length=400)),
                ('subimage3', models.ImageField(upload_to='media/')),
                ('subhead4', models.CharField(max_length=50)),
                ('subtxt4', models.CharField(max_length=400)),
                ('subimage4', models.ImageField(upload_to='media/')),
                ('lowerhead', models.CharField(max_length=30)),
                ('fsubhead1', models.CharField(max_length=25)),
                ('fsubtxt1', models.CharField(max_length=125)),
                ('fsubhead2', models.CharField(max_length=25)),
                ('fsubtxt2', models.CharField(max_length=125)),
                ('fsubhead3', models.CharField(max_length=25)),
                ('fsubtxt3', models.CharField(max_length=125)),
                ('fsubhead4', models.CharField(max_length=25)),
                ('fsubtxt4', models.CharField(max_length=125)),
            ],
        ),
    ]
