# Generated by Django 5.0.7 on 2024-08-20 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Adr', '0009_alter_masterdatamanagement_bgimage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='masterdatamanagement',
            name='Bgimage',
        ),
        migrations.RemoveField(
            model_name='masterdatamanagement',
            name='subimage2',
        ),
        migrations.RemoveField(
            model_name='masterdatamanagement',
            name='subimage3',
        ),
        migrations.RemoveField(
            model_name='masterdatamanagement',
            name='subimage4',
        ),
    ]
