# Generated by Django 5.0.7 on 2024-08-22 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adr', '0012_itesglobal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='pagename',
            field=models.CharField(max_length=200),
        ),
    ]
