# Generated by Django 5.0.7 on 2024-09-13 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adr', '0015_alter_jobforms_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobforms',
            name='lastName',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
