# Generated by Django 5.0.7 on 2024-09-13 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Adr', '0016_alter_jobforms_lastname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobforms',
            old_name='lastName',
            new_name='Phoneno',
        ),
    ]
