# Generated by Django 5.0.7 on 2024-09-13 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Adr', '0017_rename_lastname_jobforms_phoneno'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobforms',
            old_name='firstName',
            new_name='Name',
        ),
    ]
