# Generated by Django 5.0.7 on 2024-09-17 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adr', '0018_rename_firstname_jobforms_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobforms',
            name='Phoneno',
            field=models.IntegerField(blank=True, max_length='99999999999', null=True),
        ),
    ]
